server:
  port: 8088

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/research_mng_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html

#mybatis plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: null
    call-setters-on-nulls: true
#  global-config:
#    db-config:
#      #配置mybatis plus 在更新时只更新非空和非NULL的字段
#      update-strategy: not_empty

#  mapper-locations: classpath:resources/mapper/*.xml
#  type-aliases-package: com.coach.web.mapper